### PR TITLE
Expose Reader streamcut to read from given Stream Cut

### LINKED ISSUE #23: Expose StreamCut API to start reading from certain position in stream
**Problem description**
If Client application crashes and if user wants to continue read the stream from where it left then at present there is no way to get StreamCuts from ReaderGroup.
StreamCuts are set of segment/offset pairs for a single stream that represent a consistent position in the stream.

**Suggestions for an improvement**
Expose get_streamcut() API from python client

### PR DESCRIPTION
**Pull request by ShwethaSNayak**
**Change log description**  
If Client application crashes and if user wants to continue read from the stream where it left off, currently, there is no method to obtain StreamCuts from the ReaderGroup.
StreamCuts are set of segment/offset pairs for a single stream that represent a consistent position in the stream.

**Purpose of the change**  
Closes #23 

**What the code does**  
Exposed get_streamcut() API to return the Stream cut object.

**How to verify it**  
All the testcase should pass

### CODE REVIEW

File: src/stream_reader_group.rs [hunk 1]
```diff
@@ -99,6 +105,36 @@ impl PyObjectProtocol for StreamReaderGroupConfig {
     }
 }
 
+#[cfg(feature = "python_binding")]
+#[pyclass]
+#[derive(Clone)]
+pub(crate) struct ReaderStreamCut {
```
Comment (tkaitchuck) [inline src/stream_reader_group.rs]: This is a confusing name. StreamCuts are for the whole stream and not specific to a reader. We can call this StreamCut and alias the StreamCut that is being imported to something else

File: tests/pravega_reader_test.py [hunk 2]
```diff
@@ -320,3 +321,70 @@ async def test_largeEvents(self):
...
+        count=0
+        for event in segment_slice:
+            count+=1
+            print(event.data())
+            print("event offset is ")
+            print(event.offset())
+            if count == 2 :
+                break
+        self.assertEqual(count, 2, "Two events are expected")
+        time.sleep(3)
```
Comment (tkaitchuck) [inline tests/pravega_reader_test.py]: We should not depend on time, especially not in a hard coded way like this. Maybe we could have a `#[cfg(test)]` method which forces the update

**Review by tkaitchuck — CHANGES_REQUESTED** [review]

File: src/stream_reader_group.rs (hunk 1 above)
Comment (ShwethaSNayak) [reply src/stream_reader_group.rs]: Done.

**Review by tkaitchuck — APPROVED** [review]
